version: '3'
services:
  # Set the RUN_TIMESTAMP environment variable externally from the CLI, shell or from .env file.
  # SEE: https://docs.docker.com/compose/environment-variables/set-environment-variables/
  node01:
    build: .
    image: mccache-img
    container_name: mccache01
    environment:
      - MCCACHE_LEVEL=5         # Neutral
      - MCCACHE_DEBUG_FILE=/home/mccache/log/debug${RUN_TIMESTAMP}.log
      - MCCACHE_MAX_ENTRIES=${RUN_MAX_KEYS:-30} # Default to 30 key entries.
      - MCCACHE_RANDOM_SEED=1
      - MCCACHE_RUN_DURATION=${RUN_MINUTES:-3}  # Default to  3 minutes.
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
      - MCCACHE_LOG_FORMAT=%(asctime)s.%(msecs)03d %(message)s
    volumes:
      - ./log:/home/mccache/log
    command: python start_mccache.py

  node02:
    build: .
    image: mccache-img
    container_name: mccache02
    environment:
      - MCCACHE_LEVEL=5         # Neutral
      - MCCACHE_DEBUG_FILE=/home/mccache/log/debug${RUN_TIMESTAMP}.log
      - MCCACHE_MAX_ENTRIES=${RUN_MAX_KEYS:-30} # Default to 30 key entries.
      - MCCACHE_RANDOM_SEED=2
      - MCCACHE_RUN_DURATION=${RUN_MINUTES:-3}  # Default to  3 minutes.
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
      - MCCACHE_LOG_FORMAT=%(asctime)s.%(msecs)03d %(message)s
    volumes:
      - ./log:/home/mccache/log
    command: python start_mccache.py

  node03:
    build: .
    image: mccache-img
    container_name: mccache03
    environment:
      - MCCACHE_LEVEL=5         # Neutral
      - MCCACHE_DEBUG_FILE=/home/mccache/log/debug${RUN_TIMESTAMP}.log
      - MCCACHE_MAX_ENTRIES=${RUN_MAX_KEYS:-30} # Default to 30 key entries.
      - MCCACHE_RANDOM_SEED=3
      - MCCACHE_RUN_DURATION=${RUN_MINUTES:-3}  # Default to  3 minutes.
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
      - MCCACHE_LOG_FORMAT=%(asctime)s.%(msecs)03d %(message)s
    volumes:
      - ./log:/home/mccache/log
    command: python start_mccache.py

  node04:
    build: .
    image: mccache-img
    container_name: mccache04
    environment:
      - MCCACHE_LEVEL=5         # Neutral
      - MCCACHE_DEBUG_FILE=/home/mccache/log/debug${RUN_TIMESTAMP}.log
      - MCCACHE_MAX_ENTRIES=${RUN_MAX_KEYS:-30} # Default to 30 key entries.
      - MCCACHE_RANDOM_SEED=4
      - MCCACHE_RUN_DURATION=${RUN_MINUTES:-3}  # Default to  3 minutes.
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
      - MCCACHE_LOG_FORMAT=%(asctime)s.%(msecs)03d %(message)s
    volumes:
      - ./log:/home/mccache/log
    command: python start_mccache.py

  node05:
    build: .
    image: mccache-img
    container_name: mccache05
    environment:
      - MCCACHE_LEVEL=5         # Neutral
      - MCCACHE_DEBUG_FILE=/home/mccache/log/debug${RUN_TIMESTAMP}.log
      - MCCACHE_MAX_ENTRIES=${RUN_MAX_KEYS:-30} # Default to 30 key entries.
      - MCCACHE_RANDOM_SEED=5
      - MCCACHE_RUN_DURATION=${RUN_MINUTES:-3}  # Default to  3 minutes.
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
      - MCCACHE_LOG_FORMAT=%(asctime)s.%(msecs)03d %(message)s
    volumes:
      - ./log:/home/mccache/log
    command: python start_mccache.py
