version: '3'
  # Set the following environment variable externally from the CLI, shell or from .env file:
  #   TEST_APERTURE
  #   TEST_MAX_ENTRIES
  #   TEST_RUN_DURATION
  #   TEST_MONKEY_TANTRUM
  #   TEST_DEBUG_LEVEL
  #   SEE: https://docs.docker.com/compose/environment-variables/set-environment-variables/
services:
  node01:
    build: .
    image: mccache-img
    container_name: mccache01
    environment:
      - TEST_RANDOM_SEED=101
      - TEST_APERTURE=${TEST_APERTURE:-0.01}          # Default to (0.01 sec).  0.01=10ms ,0.001=1ms ,0.0005=0.5ms ,0.0001=0.1ms/100us
      - TEST_MAX_ENTRIES=${TEST_MAX_ENTRIES:-200}     # Default to 200 key entries.
      - TEST_RUN_DURATION=${TEST_RUN_DURATION:-5}     # Default to  5 minutes.
      - TEST_MONKEY_TANTRUM=${TEST_MONKEY_TANTRUM:-0} # Default to  0  percent.
      - TEST_DEBUG_LEVEL=${TEST_DEBUG_LEVEL:-0}       # Default to  0. 0=Disabled ,1=Basic ,3=Extra ,5=Surplus.
      #
      - MCCACHE_CALLBACK_WIN=3                        # 3 seconds window to alert changes.
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
#     - MCCACHE_LOG_FORMAT=%(asctime)s.%(msecs)03d [%(levelname)s] %(message)s
      - MCCACHE_LOG_FORMAT=%(created)f %(message)s
      - MCCACHE_DEBUG_LOGFILE=/home/mccache/log/debug01${RUN_TIMESTAMP}.log
      #
      - PYTHONUNBUFFERED=1  # Ensures that the python output streams are sent straight to terminal.
    volumes:
      - ./log:/home/mccache/log
      - ./src:/home/mccache/src
      - ./tests:/home/mccache/tests
    command: python tests/unit/start_mccache.py ;exit

  node02:
    build: .
    image: mccache-img
    container_name: mccache02
    environment:
      - TEST_RANDOM_SEED=127
      - TEST_APERTURE=${TEST_APERTURE:-0.01}          # Default to (0.01 sec).  0.01=10ms ,0.001=1ms ,0.0005=0.5ms ,0.0001=0.1ms/100us
      - TEST_MAX_ENTRIES=${TEST_MAX_ENTRIES:-200}     # Default to 200 key entries.
      - TEST_RUN_DURATION=${TEST_RUN_DURATION:-5}     # Default to  5 minutes.
      - TEST_MONKEY_TANTRUM=${TEST_MONKEY_TANTRUM:-0} # Default to  0  percent.
      - TEST_DEBUG_LEVEL=${TEST_DEBUG_LEVEL:-0}       # Default to  0. 0=Disabled ,1=Basic ,3=Extra ,5=Surplus.
      #
      - MCCACHE_CALLBACK_WIN=3                        # 3 seconds window to alert changes.
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
#     - MCCACHE_LOG_FORMAT=%(asctime)s.%(msecs)03d [%(levelname)s] %(message)s
      - MCCACHE_LOG_FORMAT=%(created)f %(message)s
      - MCCACHE_DEBUG_LOGFILE=/home/mccache/log/debug02${RUN_TIMESTAMP}.log
      #
      - PYTHONUNBUFFERED=1  # Ensures that the python output streams are sent straight to terminal.
    volumes:
      - ./log:/home/mccache/log
      - ./src:/home/mccache/src
      - ./tests:/home/mccache/tests
    command: python tests/unit/start_mccache.py ;exit

  node03:
    build: .
    image: mccache-img
    container_name: mccache03
    environment:
      - TEST_RANDOM_SEED=131
      - TEST_APERTURE=${TEST_APERTURE:-0.01}          # Default to (0.01 sec).  0.01=10ms ,0.001=1ms ,0.0005=0.5ms ,0.0001=0.1ms/100us
      - TEST_MAX_ENTRIES=${TEST_MAX_ENTRIES:-200}     # Default to 200 key entries.
      - TEST_RUN_DURATION=${TEST_RUN_DURATION:-5}     # Default to  5 minutes.
      - TEST_MONKEY_TANTRUM=${TEST_MONKEY_TANTRUM:-0} # Default to  0  percent.
      - TEST_DEBUG_LEVEL=${TEST_DEBUG_LEVEL:-0}       # Default to  0. 0=Disabled ,1=Basic ,3=Extra ,5=Surplus.
      #
      - MCCACHE_CALLBACK_WIN=3                        # 3 seconds window to alert changes.
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
#     - MCCACHE_LOG_FORMAT=%(asctime)s.%(msecs)03d [%(levelname)s] %(message)s
      - MCCACHE_LOG_FORMAT=%(created)f %(message)s
      - MCCACHE_DEBUG_LOGFILE=/home/mccache/log/debug03${RUN_TIMESTAMP}.log
      #
      - PYTHONUNBUFFERED=1  # Ensures that the python output streams are sent straight to terminal.
    volumes:
      - ./log:/home/mccache/log
      - ./src:/home/mccache/src
      - ./tests:/home/mccache/tests
    command: python tests/unit/start_mccache.py ;exit

  node04:
    build: .
    image: mccache-img
    container_name: mccache04
    environment:
      - TEST_RANDOM_SEED=149
      - TEST_APERTURE=${TEST_APERTURE:-0.01}          # Default to (0.01 sec).  0.01=10ms ,0.001=1ms ,0.0005=0.5ms ,0.0001=0.1ms/100us
      - TEST_MAX_ENTRIES=${TEST_MAX_ENTRIES:-200}     # Default to 200 key entries.
      - TEST_RUN_DURATION=${TEST_RUN_DURATION:-5}     # Default to  5 minutes.
      - TEST_MONKEY_TANTRUM=${TEST_MONKEY_TANTRUM:-0} # Default to  0  percent.
      - TEST_DEBUG_LEVEL=${TEST_DEBUG_LEVEL:-0}       # Default to  0. 0=Disabled ,1=Basic ,3=Extra ,5=Surplus.
      #
      - MCCACHE_CALLBACK_WIN=3                        # 3 seconds window to alert changes.
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
#     - MCCACHE_LOG_FORMAT=%(asctime)s.%(msecs)03d [%(levelname)s] %(message)s
      - MCCACHE_LOG_FORMAT=%(created)f %(message)s
      - MCCACHE_DEBUG_LOGFILE=/home/mccache/log/debug04${RUN_TIMESTAMP}.log
      #
      - PYTHONUNBUFFERED=1  # Ensures that the python output streams are sent straight to terminal.
    volumes:
      - ./log:/home/mccache/log
      - ./src:/home/mccache/src
      - ./tests:/home/mccache/tests
    command: python tests/unit/start_mccache.py ;exit

  node05:
    build: .
    image: mccache-img
    container_name: mccache05
    environment:
      - TEST_RANDOM_SEED=151
      - TEST_APERTURE=${TEST_APERTURE:-0.01}          # Default to (0.01 sec).  0.01=10ms ,0.001=1ms ,0.0005=0.5ms ,0.0001=0.1ms/100us
      - TEST_MAX_ENTRIES=${TEST_MAX_ENTRIES:-200}     # Default to 200 key entries.
      - TEST_RUN_DURATION=${TEST_RUN_DURATION:-5}     # Default to  5 minutes.
      - TEST_MONKEY_TANTRUM=${TEST_MONKEY_TANTRUM:-0} # Default to  0  percent.
      - TEST_DEBUG_LEVEL=${TEST_DEBUG_LEVEL:-0}       # Default to  0. 0=Disabled ,1=Basic ,3=Extra ,5=Surplus.
      #
      - MCCACHE_CALLBACK_WIN=3                        # 3 seconds window to alert changes.
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
#     - MCCACHE_LOG_FORMAT=%(asctime)s.%(msecs)03d [%(levelname)s] %(message)s
      - MCCACHE_LOG_FORMAT=%(created)f %(message)s
      - MCCACHE_DEBUG_LOGFILE=/home/mccache/log/debug05${RUN_TIMESTAMP}.log
      #
      - PYTHONUNBUFFERED=1  # Ensures that the python output streams are sent straight to terminal.
    volumes:
      - ./log:/home/mccache/log
      - ./src:/home/mccache/src
      - ./tests:/home/mccache/tests
    command: python tests/unit/start_mccache.py ;exit

  node06:
    build: .
    image: mccache-img
    container_name: mccache06
    environment:
      - TEST_RANDOM_SEED=163
      - TEST_APERTURE=${TEST_APERTURE:-0.01}          # Default to (0.01 sec).  0.01=10ms ,0.001=1ms ,0.0005=0.5ms ,0.0001=0.1ms/100us
      - TEST_MAX_ENTRIES=${TEST_MAX_ENTRIES:-200}     # Default to 200 key entries.
      - TEST_RUN_DURATION=${TEST_RUN_DURATION:-5}     # Default to  5 minutes.
      - TEST_MONKEY_TANTRUM=${TEST_MONKEY_TANTRUM:-0} # Default to  0  percent.
      - TEST_DEBUG_LEVEL=${TEST_DEBUG_LEVEL:-0}       # Default to  0. 0=Disabled ,1=Basic ,3=Extra ,5=Surplus.
      #
      - MCCACHE_CALLBACK_WIN=3                        # 3 seconds window to alert changes.
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
#     - MCCACHE_LOG_FORMAT=%(asctime)s.%(msecs)03d [%(levelname)s] %(message)s
      - MCCACHE_LOG_FORMAT=%(created)f %(message)s
      - MCCACHE_DEBUG_LOGFILE=/home/mccache/log/debug06${RUN_TIMESTAMP}.log
      #
      - PYTHONUNBUFFERED=1  # Ensures that the python output streams are sent straight to terminal.
    volumes:
      - ./log:/home/mccache/log
      - ./src:/home/mccache/src
      - ./tests:/home/mccache/tests
    command: python tests/unit/start_mccache.py ;exit

  node07:
    build: .
    image: mccache-img
    container_name: mccache07
    environment:
      - TEST_RANDOM_SEED=173
      - TEST_APERTURE=${TEST_APERTURE:-0.01}          # Default to (0.01 sec).  0.01=10ms ,0.001=1ms ,0.0005=0.5ms ,0.0001=0.1ms/100us
      - TEST_MAX_ENTRIES=${TEST_MAX_ENTRIES:-200}     # Default to 200 key entries.
      - TEST_RUN_DURATION=${TEST_RUN_DURATION:-5}     # Default to  5 minutes.
      - TEST_MONKEY_TANTRUM=${TEST_MONKEY_TANTRUM:-0} # Default to  0  percent.
      - TEST_DEBUG_LEVEL=${TEST_DEBUG_LEVEL:-0}       # Default to  0. 0=Disabled ,1=Basic ,3=Extra ,5=Surplus.
      #
      - MCCACHE_CALLBACK_WIN=3                        # 3 seconds window to alert changes.
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
#     - MCCACHE_LOG_FORMAT=%(asctime)s.%(msecs)03d [%(levelname)s] %(message)s
      - MCCACHE_LOG_FORMAT=%(created)f %(message)s
      - MCCACHE_DEBUG_LOGFILE=/home/mccache/log/debug07${RUN_TIMESTAMP}.log
      #
      - PYTHONUNBUFFERED=1  # Ensures that the python output streams are sent straight to terminal.
    volumes:
      - ./log:/home/mccache/log
      - ./src:/home/mccache/src
      - ./tests:/home/mccache/tests
    command: python tests/unit/start_mccache.py ;exit

  node08:
    build: .
    image: mccache-img
    container_name: mccache08
    environment:
      - TEST_RANDOM_SEED=181
      - TEST_APERTURE=${TEST_APERTURE:-0.01}          # Default to (0.01 sec).  0.01=10ms ,0.001=1ms ,0.0005=0.5ms ,0.0001=0.1ms/100us
      - TEST_MAX_ENTRIES=${TEST_MAX_ENTRIES:-200}     # Default to 200 key entries.
      - TEST_RUN_DURATION=${TEST_RUN_DURATION:-5}     # Default to  5 minutes.
      - TEST_MONKEY_TANTRUM=${TEST_MONKEY_TANTRUM:-0} # Default to  0  percent.
      - TEST_DEBUG_LEVEL=${TEST_DEBUG_LEVEL:-0}       # Default to  0. 0=Disabled ,1=Basic ,3=Extra ,5=Surplus.
      #
      - MCCACHE_CALLBACK_WIN=3                        # 3 seconds window to alert changes.
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
#     - MCCACHE_LOG_FORMAT=%(asctime)s.%(msecs)03d [%(levelname)s] %(message)s
      - MCCACHE_LOG_FORMAT=%(created)f %(message)s
      - MCCACHE_DEBUG_LOGFILE=/home/mccache/log/debug08${RUN_TIMESTAMP}.log
      #
      - PYTHONUNBUFFERED=1  # Ensures that the python output streams are sent straight to terminal.
    volumes:
      - ./log:/home/mccache/log
      - ./src:/home/mccache/src
      - ./tests:/home/mccache/tests
    command: python tests/unit/start_mccache.py ;exit

  node09:
    build: .
    image: mccache-img
    container_name: mccache09
    environment:
      - TEST_RANDOM_SEED=191
      - TEST_APERTURE=${TEST_APERTURE:-0.01}          # Default to (0.01 sec).  0.01=10ms ,0.001=1ms ,0.0005=0.5ms ,0.0001=0.1ms/100us
      - TEST_MAX_ENTRIES=${TEST_MAX_ENTRIES:-200}     # Default to 200 key entries.
      - TEST_RUN_DURATION=${TEST_RUN_DURATION:-5}     # Default to  5 minutes.
      - TEST_MONKEY_TANTRUM=${TEST_MONKEY_TANTRUM:-0} # Default to  0  percent.
      - TEST_DEBUG_LEVEL=${TEST_DEBUG_LEVEL:-0}       # Default to  0. 0=Disabled ,1=Basic ,3=Extra ,5=Surplus.
      #
      - MCCACHE_CALLBACK_WIN=3                        # 3 seconds window to alert changes.
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
#     - MCCACHE_LOG_FORMAT=%(asctime)s.%(msecs)03d [%(levelname)s] %(message)s
      - MCCACHE_LOG_FORMAT=%(created)f %(message)s
      - MCCACHE_DEBUG_LOGFILE=/home/mccache/log/debug09${RUN_TIMESTAMP}.log
      #
      - PYTHONUNBUFFERED=1  # Ensures that the python output streams are sent straight to terminal.
    volumes:
      - ./log:/home/mccache/log
      - ./src:/home/mccache/src
      - ./tests:/home/mccache/tests
    command: python tests/unit/start_mccache.py ;exit
