version: '3'
services:
  # Set the RUN_TIMESTAMP environment variable externally from the CLI, shell or from .env file.
  # SEE: https://docs.docker.com/compose/environment-variables/set-environment-variables/
  node01:
    build:  .
    container_name: mccache01
    environment:
      - MCCACHE_LEVEL=5         # Neutral
      - MCCACHE_DEBUG_FILE=/home/mccache/tests/log/mccache/debug${RUN_TIMESTAMP}.log
      - MCCACHE_MAX_ENTRIES=10
      - MCCACHE_RANDOM_SEED=1
      - MCCACHE_RUN_DURATION=3  # Minutes
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
    #network_mode: host
    volumes:
      # .:/home/mccache/tests
      - ./log:/var/log/mccache
    command: sleep 15s

  node02:
    build:  .
    container_name: mccache02
    environment:
      - MCCACHE_LEVEL=5         # Neutral
      - MCCACHE_DEBUG_FILE=/home/mccache/tests/log/mccache/debug${RUN_TIMESTAMP}.log
      - MCCACHE_MAX_ENTRIES=10
      - MCCACHE_RANDOM_SEED=2
      - MCCACHE_RUN_DURATION=3  # Minutes
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
    #network_mode: host
    volumes:
      # .:/home/mccache/tests
      - ./log:/var/log/mccache
    command: sleep 15s

  node03:
    build:  .
    container_name: mccache03
    environment:
      - MCCACHE_LEVEL=5         # Neutral
      - MCCACHE_DEBUG_FILE=/home/mccache/tests/log/mccache/debug${RUN_TIMESTAMP}.log
      - MCCACHE_MAX_ENTRIES=10
      - MCCACHE_RANDOM_SEED=3
      - MCCACHE_RUN_DURATION=3  # Minutes
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
    #network_mode: host
    volumes:
      # .:/home/mccache/tests
      - ./log:/var/log/mccache
    command: sleep 15s

  node04:
    build:  .
    container_name: mccache04
    environment:
      - MCCACHE_LEVEL=5         # Neutral
      - MCCACHE_DEBUG_FILE=/home/mccache/tests/log/mccache/debug${RUN_TIMESTAMP}.log
      - MCCACHE_MAX_ENTRIES=10
      - MCCACHE_RANDOM_SEED=4
      - MCCACHE_RUN_DURATION=3  # Minutes
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
    #network_mode: host
    volumes:
      # .:/home/mccache/tests
      - ./log:/var/log/mccache
    command: sleep 15s

  node05:
    build:  .
    container_name: mccache05
    environment:
      - MCCACHE_LEVEL=5         # Neutral
      - MCCACHE_DEBUG_FILE=/home/mccache/tests/log/mccache/debug${RUN_TIMESTAMP}.log
      - MCCACHE_MAX_ENTRIES=10
      - MCCACHE_RANDOM_SEED=5
      - MCCACHE_RUN_DURATION=3  # Minutes
      - MCCACHE_MULTICAST_IP=224.0.0.3:4000
    #network_mode: host
    volumes:
      # .:/home/mccache/tests
      - ./log:/var/log/mccache
    command: sleep 15s
